### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by joshbowyer** [tchx84/Portfolio#19]
An option to toggle to dark mode would be good, and also maybe an optional "icon color" setting.

**Comment by tchx84** [comment]
You mean something like this?

![image](https://user-images.githubusercontent.com/481418/102949234-8a457600-44a6-11eb-8d4f-0f537a19a1ad.png)

**Comment by joshbowyer** [comment]
Yes that looks perfect!

**Comment by GustavoPeredo** [comment]
Hey @tchx84 have you approved this idea? I can implement it (PS: Glad to see an screenshot with my app :D )

**Comment by tchx84** [comment]
@GustavoPeredo hah, is a great example.

To be honest, I am still on the fence regarding this request...

The reason is that the menu space is very limited already (see screenshot below) and I _really_ don't want Portfolio to have a separate settings screen/dialog or anything like that. Simplicity and minimalism is the core value proposition for this app.

![Screenshot from 2021-01-18 16-38-25](https://user-images.githubusercontent.com/481418/104956904-d43d5100-59ab-11eb-8565-7513313d23bf.png)

I would re-consider it if we could a way to make it fit in without taking too much space and, somehow, making it look less prominent so it doesn't distract from the key-options.

**Comment by GustavoPeredo** [comment]
I think a possible solution would be to have it as a hidden setting (for now), similarly to how [Unrud's Video Downloader does with MPEG](https://github.com/Unrud/video-downloader#prefer-mpeg).

This way, although dark mode would be implemented, it wouldn't occupy any ui space. But why implement it, then? Personally I have two reasons:

1- Allow users to have  dark mode in a fairly accessible way (run a command on terminal or edit the value using dconf)
2- Push the system-wide dark mode agenda (lol), which the most promising way seems to be a [dbus call](https://blog.elementary.io/dark-style-progress/).

**Comment by tchx84** [comment]
Just for the record, Portfolio will always pick whatever theme and variant you set in your system, e.g.

```
$ gsettings set org.gnome.desktop.interface gtk-theme "Adwaita-dark"
```

and you get:

![image](https://user-images.githubusercontent.com/481418/106360591-0332bb80-62f8-11eb-9628-e7d4d8af29b6.png)
